// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: piano_tiles

#include "ui.h"

// void tile_event(lv_event_t * e)
// {
// 	// Your code here
// }
